onboarding = false

[ui]
agent_panel_scope = "all"
agent_panel_sort = "spaces"
prompt_new_tab_name = false

[ui.toast]
delivery = "herdr"

[theme]
name = "gruvbox"

[experimental]
pane_history = true
switch_ascii_input_source_in_prefix = true
kitty_graphics = true

[keys]
prefix = "cmd+k"

settings = ["prefix+s", "prefix+ы"]

new_workspace = "cmd+n"
split_vertical = "cmd+d"
split_horizontal = "cmd+shift+d"
switch_tab = "cmd+1..9"
switch_workspace = "ctrl+1..9"
next_tab = "cmd+]"
previous_tab = "cmd+["

focus_pane_left = "cmd+alt+h"
focus_pane_down = "cmd+alt+j"
focus_pane_up = "cmd+alt+k"
focus_pane_right = "cmd+alt+l"

zoom = "cmd+enter"
close_workspace = "cmd+shift+w"
toggle_sidebar = "cmd+b"

rename_tab = "cmd+r"
rename_workspace = "cmd+shift+r"
rename_pane = "cmd+alt+r"

[[keys.command]]
key = "cmd+t"
type = "shell"
command = "python3 ${XDG_CONFIG_HOME:-$HOME/.config}/herdr/scripts/open-from-current-cwd.py tab"

[[keys.command]]
key = "cmd+ctrl+h"
type = "shell"
command = "/opt/homebrew/bin/herdr pane resize --current --direction left --amount 0.05"

[[keys.command]]
key = "cmd+ctrl+l"
type = "shell"
command = "/opt/homebrew/bin/herdr pane resize --current --direction right --amount 0.05"

[[keys.command]]
key = "cmd+ctrl+k"
type = "shell"
command = "/opt/homebrew/bin/herdr pane resize --current --direction up --amount 0.05"

[[keys.command]]
key = "cmd+ctrl+j"
type = "shell"
command = "/opt/homebrew/bin/herdr pane resize --current --direction down --amount 0.05"

[[keys.command]]
key = ["prefix+k", "prefix+л"]
type = "shell"
command = "python3 ${XDG_CONFIG_HOME:-$HOME/.config}/herdr/scripts/clear-pane.py"

[[keys.command]]
key = "cmd+w"
type = "shell"
command = "python3 ${XDG_CONFIG_HOME:-$HOME/.config}/herdr/scripts/cmd-w.py"

